services:
  mysql-image:
    container_name: Database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: zxcvbnm
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent","--password=zxcvbnm"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 20s
    
  backend:
    build:
      context: . 
    container_name: node
    ports:
       - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      mysql-image:
        condition: service_healthy
    restart: on-failure
    stdin_open: true
    tty: true


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start